---

- name: Pull Fedora image from {{ url }}
  hosts: localhost
  become: yes

  vars:
    url: "quay.io"
    
  tasks:
    - name: Pull Fedora 44 container
      containers.podman.podman_image:
        name: "{{ url }}/fedora/fedora-bootc:44"
